name: DevOps Pipeline

# Crear las siguientes variables como secrets dentro del settings del proyecto
# GITHUB_TOKEN es un token de github que se puede crear con otro nombre de ser necesario, recordar colocar el nombre en el main.yml
# SONAR_TOKEN es un token que se genera en sonarcloud
# FTP_SERVER servidor de hostinger
# FTP_USERNAME usuario de ftp de hostinger
# FTP_PASSWORD contraseña del usuario de ftp
# Deploy staging hay que agregar la URL de la web de staging Ej: https://example.com , la URL sin comillas debe ir
# Author: Gaston Barbaccia

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main


jobs:
  gitleaks:
      name: Gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: gastonbarbaccia/gitleaks@v2.1
          env:
            GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        - name: Get the output from the gitleaks step
          run: |
            echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
            echo "result: ${{ steps.gitleaks.outputs.result }}"
            echo "output: ${{ steps.gitleaks.outputs.output }}"
            echo "command: ${{ steps.gitleaks.outputs.command }}"
            echo "report: ${{ steps.gitleaks.outputs.report }}"
        - name: Upload SARIF report
          if: steps.gitleaks.outputs.exitcode == 1
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: ${{ steps.gitleaks.outputs.report }} 

  copy_paste_detector:
    name: Copy Paste Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Copy Paste Detector
        uses: StephaneBour/actions-php-cpd@1.0
        with:
          dir: "src/"

  phpstan:
    name: PHP Stan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/phpstan@v3
        with:
          path: "src/"

  php_lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Syntax Checker (Lint)
        uses: StephaneBour/actions-php-lint@7.4
        with:
          dir: "src/"

  sonarcloud:
    name: Sonarcloud
    runs-on: ubuntu-latest
    needs: [gitleaks,copy_paste_detector, phpstan, php_lint]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/
  #           args: >
  #              -Dsonar.organization=my-organization
  #              -Dsonar.projectKey=my-projectkey
  #              -Dsonar.python.coverage.reportPaths=coverage.xml
  #              -Dsonar.sources=lib/
  #              -Dsonar.test.exclusions=tests/**
  #              -Dsonar.tests=tests/
  #              -Dsonar.verbose=true
  

  dependency_check:
    name: Dependency check Scan
    runs-on: ubuntu-latest
    needs: [gitleaks,copy_paste_detector, phpstan, php_lint]
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "test"
          path: "src/"
          format: "HTML"
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
          name: Depcheck report
          path: ${{github.workspace}}/reports

  Deploy_staging:
    name: Deploy Staging
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://example.com
    needs: [sonarcloud,dependency_check]
    steps:
      - uses: actions/checkout@v2
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "src/"
          remoteDir: "."